#!/usr/bin/env python
# ebs-tools, a set of tools to manage EBS volumes and snapshots
#
# Copyright (C) 2014 Julio Gonzalez Gil <julio@juliogonzalez.es>
#
# This file is part of ebs-tools.
#
# ebs-tools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ebs-tools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ebs-tools.  If not, see <http://www.gnu.org/licenses/>.


from lib.check import print_usage_error
from lib.exceptions import OptionNotPresent, OptionsAlternativesNotPresent
from lib.messages import print_error, print_info, print_ok, print_warning
from lib.tasks import task_create_snapshots_ec2
from optparse import OptionParser
from os import path


def parse_options():
    """ Parse and validate options
    Args:
        None
    Returns:
        A dictionary with all the options
    Raises:
        OptionNotPresent: If a mandatory option was not present
    """
    usage = "%prog <arguments>"
    description = ('Tool to create EBS snapshots for one or more volumes for '
                   'an instance')
    parser = OptionParser(usage=usage, description=description)
    parser.add_option('--instance-id', action='store',
                      help='EC2 instance-id')
    parser.add_option('--instance_name', action='store',
                      help='EC2 instance name')
    parser.add_option('--devices', action='store',
                      help='Attached devices to snapshot. Use regular'
                           'expressions. For example /dev/sd[b-c] to catch'
                           '/dev/sdb* and /dev/sdc*')
    parser.add_option('--volume_name', action='store',
                      help='Regular expression to select volumes to snapshot '
                           'by name. For example volume1 to catch'
                           'volume1*')
    parser.add_option('--region', action='store',
                      help='AWS Region where the volume is located')
    parser.add_option('--name', action='store',
                      help='Name for the new snapshots [Optional, default will'
                           ' be the volume name if available, or the volume ID'
                           ' otherwise]')
    parser.add_option('--description', action='store',
                      help='Description for the new snapshots [Optional,'
                           ' default will be instance name/ID and attachment'
                           ' info]')
    parser.add_option('--parallel', action='store_false',
                      help='Perform snapshots in parallel')
    parser.add_option('--savetags', action='store_false',
                      help='When present, copy volume tags to the snapshots '
                           '(except Name)')
    parser.add_option('--dry', action='store_false',
                      help='Simulate functionality at AWS')
    (options, args) = parser.parse_args()
    if options.instance_id is None and options.instance_name is None:
        raise OptionsAlternativesNotPresent('instance_id', 'instance_name')
    if options.devices is None and options.volume_name is None:
        raise OptionsAlternativesNotPresent('devices', 'volume_name')
    if options.region is None:
        raise OptionNotPresent('region')
    if options.parallel is None:
        options.parallel = False
    else:
        options.parallel = True
    if options.savetags is None:
        options.savetags = False
    else:
        options.savetags = True
    if options.dry is None:
        options.dry = False
    else:
        options.dry = True
    return(options)


def main():
    try:
        args = parse_options()
    except Exception as e:
        print_usage_error(path.basename(__file__), e)
        exit(1)
    try:
        task_create_snapshots_ec2(args.region, args.instance_id,
                                  args.instance_name, args.parallel,
                                  args.dry, args.devices, args.volume_name,
                                  args.name, args.description, args.savetags)
    except Exception as e:
        print_error(e)
        exit(2)

if __name__ == "__main__":
    main()
